---
# tasks file for usb-checker-role


  - name: Install ntfs packages
    ansible.builtin.yum:
      name: ntfs*
      state: present

  - name: Install usbutils
    ansible.builtin.yum:
      name: usbutils
      state: present

  - name: Run USB checker script
    ansible.builtin.script: "~/usb-pluged-in-check.sh"




